use walkdir::WalkDir;
use std::fs;
use std::path::{Path, PathBuf};
use crate::FfiStorageTarget;

pub fn get_home_dir() -> PathBuf {
    dirs::home_dir().unwrap_or_else(|| PathBuf::from("/"))
}

pub fn scan_storage() -> Vec<FfiStorageTarget> {
    let home = get_home_dir();
    
    let mut targets = vec![
        FfiStorageTarget {
            id: "caches".to_string(),
            name: "Application Caches".to_string(),
            category: "System & App Junk".to_string(),
            description: "Temporary cached files generated by macOS applications".to_string(),
            path: home.join("Library/Caches").to_string_lossy().into_owned(),
            size_bytes: 0,
            default_checked: true,
        },
        FfiStorageTarget {
            id: "logs".to_string(),
            name: "System & App Logs".to_string(),
            category: "System & App Junk".to_string(),
            description: "Diagnostic log files and crash reports".to_string(),
            path: home.join("Library/Logs").to_string_lossy().into_owned(),
            size_bytes: 0,
            default_checked: true,
        },
        FfiStorageTarget {
            id: "trash".to_string(),
            name: "Trash Bin".to_string(),
            category: "System & App Junk".to_string(),
            description: "Files currently waiting in your user Trash bin".to_string(),
            path: home.join(".Trash").to_string_lossy().into_owned(),
            size_bytes: 0,
            default_checked: true,
        },
        FfiStorageTarget {
            id: "xcode-derived".to_string(),
            name: "Xcode DerivedData".to_string(),
            category: "Developer & Build".to_string(),
            description: "Intermediate build results, indexes, and symbol files for Xcode".to_string(),
            path: home.join("Library/Developer/Xcode/DerivedData").to_string_lossy().into_owned(),
            size_bytes: 0,
            default_checked: true,
        },
        FfiStorageTarget {
            id: "xcode-device-support".to_string(),
            name: "iOS Device Support".to_string(),
            category: "Developer & Build".to_string(),
            description: "Cached iOS debugging symbols for older connected devices".to_string(),
            path: home.join("Library/Developer/Xcode/iOS DeviceSupport").to_string_lossy().into_owned(),
            size_bytes: 0,
            default_checked: true,
        },
        FfiStorageTarget {
            id: "homebrew-cache".to_string(),
            name: "Homebrew Downloads".to_string(),
            category: "Developer & Build".to_string(),
            description: "Cached formula bottle downloads and source packages".to_string(),
            path: home.join("Library/Caches/Homebrew").to_string_lossy().into_owned(),
            size_bytes: 0,
            default_checked: true,
        },
        FfiStorageTarget {
            id: "npm-cache".to_string(),
            name: "npm Cache".to_string(),
            category: "Package Managers".to_string(),
            description: "Downloaded npm tarballs and cache".to_string(),
            path: home.join(".npm/_cacache").to_string_lossy().into_owned(),
            size_bytes: 0,
            default_checked: true,
        },
        FfiStorageTarget {
            id: "pip-cache".to_string(),
            name: "Pip Cache".to_string(),
            category: "Package Managers".to_string(),
            description: "Cached Python wheel packages".to_string(),
            path: home.join("Library/Caches/pip").to_string_lossy().into_owned(),
            size_bytes: 0,
            default_checked: true,
        },
        FfiStorageTarget {
            id: "docker-data".to_string(),
            name: "Docker Containers & Images".to_string(),
            category: "Containers & IDEs".to_string(),
            description: "Docker Desktop virtual disk and cache".to_string(),
            path: home.join("Library/Containers/com.docker.docker/Data").to_string_lossy().into_owned(),
            size_bytes: 0,
            default_checked: false,
        },
    ];

    // Calculate sizes
    for target in &mut targets {
        target.size_bytes = get_dir_size(Path::new(&target.path));
    }

    // Filter out targets that don't exist or are empty (size == 0)
    targets.into_iter().filter(|t| t.size_bytes > 0).collect()
}

fn get_dir_size(path: &Path) -> u64 {
    use std::os::unix::fs::MetadataExt;
    
    if !path.exists() {
        return 0;
    }
    
    let mut total_size = 0;
    for entry in WalkDir::new(path).into_iter().filter_map(|e| e.ok()) {
        if let Ok(metadata) = entry.metadata() {
            if metadata.is_file() && !metadata.file_type().is_symlink() {
                // Use blocks to correctly calculate physical size for sparse files (like Docker disks)
                // blocks() returns the number of 512-byte blocks allocated to the file
                total_size += metadata.blocks() * 512;
            }
        }
    }
    total_size
}

pub fn clean_storage_targets(paths: Vec<String>) -> Result<u64, String> {
    let mut cleaned_bytes = 0;
    
    for path_str in paths {
        let path = Path::new(&path_str);
        if !path.exists() {
            continue;
        }
        
        let size_before = get_dir_size(path);
        
        // Read the directory and delete contents, keeping the parent directory itself
        if let Ok(entries) = fs::read_dir(path) {
            for entry in entries.filter_map(|e| e.ok()) {
                let entry_path = entry.path();
                if entry_path.is_dir() {
                    let _ = fs::remove_dir_all(&entry_path); // Ignore individual failures
                } else {
                    let _ = fs::remove_file(&entry_path);
                }
            }
        }
        
        let size_after = get_dir_size(path);
        cleaned_bytes += size_before.saturating_sub(size_after);
    }
    
    Ok(cleaned_bytes)
}
